### PR TITLE
Fix/137 cover center

### LINKED ISSUE #137: Fix CoverCenter
Adjust cover center, stacktrace: 

```
Crashed: com.apple.main-thread
0  smplayer                       0x12aa0 $s8smplayer11CoverCenterC03getB4Path33_71F058CFF50F24495D1FACFF0857BBC6LL7albumId3urlS2S_SStFTf4nnd_n + 1204
1  smplayer                       0x12ac8 $s8smplayer11CoverCenterC03getB9FromCache33_71F058CFF50F24495D1FACFF0857BBC6LL7albumId3urlSo6NSDataCSgSS_SStFTf4nnd_n + 36
2  smplayer                       0x11818 $s8smplayer11CoverCenterC03getB033_71F058CFF50F24495D1FACFF0857BBC6LL4item3urlSo18MPMediaItemArtworkCSgAA08PlaylistN0CSg_SStF + 116
3  smplayer                       0x13a38 $s8smplayer16NowPlayingCenterC3set4itemyAA12PlaylistItemCSg_tFZyyScMYccfU_ + 1056
4  smplayer                       0x1224c $sIeg_IeyB_TR + 28
5  libdispatch.dylib              0x63094 _dispatch_call_block_and_release + 24
6  libdispatch.dylib              0x64094 _dispatch_client_callout + 16
7  libdispatch.dylib              0x10d44 _dispatch_main_queue_drain + 928
8  libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp + 36
9  CoreFoundation                 0x4e014 <redacted> + 12
10 CoreFoundation                 0xb4f8 <redacted> + 2544
11 CoreFoundation                 0x1e174 CFRunLoopRunSpecific + 572
12 GraphicsServices               0x1988 GSEventRunModal + 160
13 UIKitCore                      0x4e5a88 <redacted> + 1080
14 UIKitCore                      0x27ef78 UIApplicationMain + 336
15 Runner                         0x90e0 main + 7 (main.m:7)
16 ???                            0x1055204d0 (Ausente)
```

### PR DESCRIPTION
**Pull request by felipecastrosales**
closes #137

### Summary by CodeRabbit

---
**Release Notes for Pull Request**

- **Performance Improvement**: Updated `getCoverFromWeb` function to use `URLSession.shared.dataTask(with:completionHandler:)` for asynchronous data retrieval from web URLs, enhancing the app's responsiveness.
- **Bug Fix**: Improved error handling in `getCoverPath` and `getCoverFromWeb` functions to manage failed directory creation and network requests respectively, ensuring smoother user experience.
- **New Feature**: Added `uiImageToAssetString` function to convert a `UIImage` to a base64-encoded string, expanding the functionality of the plugin.
- **Refactor**: Moved `saveToLocalCache` function execution to a background queue for better performance and responsiveness.
- **Chore**: Updated podspec file to include additional resource files (storyboard, xib, png) in the Flutter plugin project build, ensuring all necessary resources are packaged with the plugin.

### CODE REVIEW

File: packages/player/ios/Classes/CoverCenter.swift [hunk 1]
```diff
@@ -112,15 +112,26 @@ extension String {
     }
     
     private func getCoverFromWeb(url: String) -> NSData? {
-        do {
-            let data = try NSData.init(contentsOf: URL.init(string: url)!, options: Data.ReadingOptions.mappedIfSafe)
+        if let url = URL(string: url) {
+            let semaphore = DispatchSemaphore(value: 0)
+            var data: NSData? = nil
+            let task = URLSession.shared.dataTask(with: url) { (taskData, response, error) in
```
Comment (felipecastrosales) [inline packages/player/ios/Classes/CoverCenter.swift:118]: Now using URLSession because this: 

image

I think that this can be relations or could be a future problem.

**Review by atrope — APPROVED** [review]

**Review by lstonussi — APPROVED** [review]
